### ISSUE TITLE
Sellmeier coefficients

### ISSUE THREAD

**Issue by shkoch** [lbolla/EMpy#17]
Hello.
Sellmeier coefficient is defined by 
(in form of)
**n^2** = constant + B1 wl ^2 /(wl^2-C1) + B2 wl ^2 /(wl^2-C2) +B3 wl ^2 /(wl^2-C3)
as written in [Wiki](https://en.wikipedia.org/wiki/Sellmeier_equation)

But in materials.py, Sellmeier equation is written by
> Set the rix dispersion function to the 6-parameter Sellmeier
>         function as so:
>             **n(wls)** =  1. +
>             B1 * wls ** 2 / (wls ** 2 - C1) +
>             B2 * wls ** 2 / (wls ** 2 - C2) +
>             B3 * wls ** 2 / (wls ** 2 - C3)

Sellmeier is about to "the square of refractive index" but the comments in the Method describe it as "the refractive index" itself.
I checked
def __from_sellmeier(n0_smcoeffs, wls)
 I can see the script is right but the only description is wrong.
So the description should be updated correctly.

Thanks

**Comment by lbolla** [comment]
Fixed, thanks!
