### ISSUE TITLE
RefractiveIndex(n0_func=...): passes Ones to RIX function

### ISSUE THREAD

**Issue by demisjohn** [lbolla/EMpy#19]
@lbolla : I found a bug in `RefractiveIndex.__from_function()`, in which the function erroneously passed an array of ones `[1,1,1...]` via the `numpy.ones_like(...)` value, instead of the actual wavelength values `[1.55e-6,1.54e-6...]`, to the RIX function supplied by the user.

In my recent fork (to add laser monitor example), I've updated this to `return n0_func(wls) * numpy.ones_like(wls)` similar to your other functions.  
See https://github.com/demisjohn/EMpy/commit/7813056e58b0d4872e176b3593c503f5b4ac9ce2

However, I'm wondering why you multiply the wavelengths `wls` by `numpy.ones_like()` in the first place.  What is the purpose of this? Should I omit that entirely?

**Comment by lbolla** [comment]
The idea of

**Comment by lbolla** [comment]
By the way, the idea behind `n0_func` is to return and accept an np array, as the docstring says: https://github.com/lbolla/EMpy/blob/master/EMpy/materials.py#L63-L81

**Comment by demisjohn** [comment]
Hmmm... I had just rebased from this repo before I started working on this. That would be unfortunately if I'm working on old code - will check.  Thanks for the info.
