### ISSUE TITLE
EMPy Citation

### ISSUE THREAD

**Issue by DanHickstein** [lbolla/EMpy#22]
I'm working on a paper where I present some results calculated using EMPy. Is there a preferred way that EMPy should be cited?

**Comment by lbolla** [comment]
I don't have a preferred way, no. But I added a suggested citation in the README (https://github.com/lbolla/EMpy/commit/6127c0e45481bacecc76c401a2b39f8891edf47e).

Thanks a lot for the citation!

**Comment by DanHickstein** [comment]
Thanks!
