### ISSUE TITLE
EMpy installation downgrades matplotlib

### ISSUE THREAD

**Issue by DanHickstein** [lbolla/EMpy#23]
Currently, installing EMpy downgrades my matplotlib 2.0 to 1.5.x. Is there a reason that EMpy is not compatible with matplotlib 2.0?

In general, it seems weird that [setup.py](https://github.com/lbolla/EMpy/blob/master/setup.py) specifies maximum version numbers for the required packages. Typically, minimum version numbers are specified. (I.e., should the `<` signs be `>`?)
```
    install_requires=[
        'distribute>=0.6.28',
        'future<1.0dev',
        'numpy<2.0dev',
        'scipy<1.0dev',
        'matplotlib<2.0dev',
    ],
```

**Comment by lbolla** [comment]
It's normally safer to assume libraries to use "semver" and exclude the next major version which would include backward-incompatible changes.
If, upon testing, version 2 works fine, we can unpin it.
Happy to accept a PR.

**Comment by Chronum94** [comment]
I ran it with matplotlib 2.2.0 and the tests/examples run fine. I'd send a PR, but I've made significant other changes to the code (none of which should break it, but I'm testing that).

**Comment by lbolla** [comment]
@Chronum94 thanks! Can you please make a single simple PR to upgrade matplotlib and a different PR for the other changes?

**Comment by YagoDel** [comment]
A bit late to the party, but just checked that everything works and made a simple PR. The only example that is a bit different is ex_RCWA.py and the scipy.linalg.linsolve is throwing a "LinAlgWarning: Ill-conditioned matrix [...] result may not be accurate"

**Comment by lbolla** [comment]
Unpinned all deps in master. Deps in requirement files are managed using pip-tools (see Makefile targets to bump them).
