### ISSUE TITLE
Outdated dependency?

### ISSUE THREAD

**Issue by pfjarschel** [lbolla/EMpy#24]
First of all, good work on this!!! It's almost like a dream come true!

Anyway, I'm really new to Python, so maybe I was doing something very wrong. I'm on Manjaro Linux (Arch-based), using Python 3.6. I tried installing the module from pip, but it always failed when installing the "distribute" package. Searching about it, I found that it is now simply a compatibility layer that installs SetupTools, which was already installed.

So, using "--no-deps" with pip enabled me to install EMpy, and it's working beautifully! So maybe it's an unecessary dependency?

**Comment by lbolla** [comment]
Thanks! Indeed, distribute is an ancient relic. Removing it should be harmless.

**Comment by lbolla** [comment]
EMpy==1.3.0 is out.
