### ISSUE TITLE
ex_modesolver_2: coordinates rotated?

### ISSUE THREAD

**Issue by demisjohn** [lbolla/EMpy#25]
I'm trying to use your modesolver example #2 with the "CrossSection" & "Slices" method that I like very much (`ex_modesolver_2.py`).
Your example only plots the mode versus grid/mesh points - the spatial dimension is missing.

If I insert the variables `X` & `Y` into the `contourf` function, the `solver.modes[0].Ex` array then doesn't match the `X` & `Y` arrays, I have to use `numpy.rot90()` to get it to plot, indicating that the X & Y axes are flipped for some reason (and the mode shows up sideways).
(Also I have to strip one point off from each X/Y array, as `CrossSection.grid()` is one value larger in each direction than the `solver.modes[0].Ex` array.)

I am thus unable to figure out which way is the expected "up/down/left/right" in this example, it doesn't seem to match the passed X & Y arrays.

Is `VFDModeSolver.solve()` returning the modes sideways, and missing one point in each dimension?  Is it also solving them sideways?

**Comment by lbolla** [comment]
The mode solver uses finite-differences on a staggered grid, so E and H fields are located on different points on the grid: nodes, vertical edges or horizontal edges. That is the reason why they don't have the same dimensions. You can of course interpolate the values on any (x,y) point you need using one of the scipy's interp functions.

**Comment by demisjohn** [comment]
I see, that makes sense about the extra data point.  
However, what's going on with the 90° rotation?

Can you post the code you used to make the spatial field plots on the [web page, here](http://lbolla.github.io/EMpy/#example_modesolver)?  I believe the code there also only plots versus grid number, not spatial dimension like the plots shown.

That would probably clarify things.
Thanks!

**Comment by lbolla** [comment]
You can use `FDMode.get_field` to interpolate a mode where needed. I had to fix a bug in that function, though. Also, I've updated the example in http://lbolla.github.io/EMpy/#example_modesolver
