### ISSUE TITLE
Is EMpy able to simulate gap ring resonator? 

### ISSUE THREAD

**Issue by shinong** [lbolla/EMpy#26]
Hi all, 
Just wondering whether the EMpy is capable of SRR simulaiton? I saw the example for ring resonators but I am unclear about how to model a gap ring in EMpy. 

Thanks,
Shinong

**Comment by lbolla** [comment]
Yes, Single Ring Resonators are supported. There is an example in https://github.com/lbolla/EMpy/blob/master/examples/ex_SRR.py

What do you mean by "gap ring"?

**Comment by shinong** [comment]
Hi Ibolla,
Thank you so much for your generous help. In my case, I am designing a loop with a 'gap' feature (also known as split ring resonator) and I notice in your example, it is just a closed ring which operates at a much higher frequency. I am wondering how I can creat the 'gap' feature onto the ring? 
![maxresdefault](https://user-images.githubusercontent.com/12669268/40991497-f5201bf6-68c1-11e8-9268-94bb4164da51.jpg)

**Comment by lbolla** [comment]
Interesting structure. Unfortunately, EMpy cannot simulate those.
If you implement some code, let me know and I'll be happy to merge it.
