### ISSUE TITLE
2D  binary grating consists of a cylinder

### ISSUE THREAD

**Issue by BrandonHanx** [lbolla/EMpy#29]
Thanks for the excellent work. 
I am a new on metasurface. I wanna define a meta-atom consists of a cylinder with a glass substrate, which is a periodic unit of a 2D binary grating, and I wanna get the transmittance of the plane wave with different frequencies. [Here]( https://box.zjuqsc.com/-48402925 ) is the model I made in Lumerical FDTD solutions. 
Is there any example that is similar to this task that I can refer to?

**Comment by lbolla** [comment]
Sorry, there are no examples of such structures in EMpy. You mention FDTD: EMpy does not implement that method. What method from EMpy would you like to use?

**Comment by BrandonHanx** [comment]
I just modeled the structure desired using FDTD. All methods which can solve EM response will be ok for me, such as FDTD, RCWA or FEM and so on.

**Comment by lbolla** [comment]
EMpy's RCWA is 1D and FEM is not implemented. I used to use an algorithm based on Bessel function expansion to solve such structures, but it's not included in EMpy.

**Comment by BrandonHanx** [comment]
Ok, I get it. Thanks anyway.
