### ISSUE TITLE
Simulation result of tar.gz and zip file are different

### ISSUE THREAD

**Issue by Tomatolism** [lbolla/EMpy#32]
First of all, Thank for the excellent work!

I downloaded the tar.gz and the zip file from [Homepage](http://lbolla.github.io/EMpy/), 
and install EMpy in both way.
(Installing tar.gz by pip, and adding sys.path to directory of decompressed zip file.)

I try to do some RCWA calculation.
For Layer both method came to the same result.
However, when it came to BinaryGrating and AsymmetricDoubleGrating,
the tar.gz one and zip one have different DE1 and DE3 result. 
Comparing to my reference data, it seems the tar.gz's result is correct.

I'd like to know if anyone encountered the same problem?
And I'm try to found out the bug in github, however, haven't gotten an idea.
Do anyone have any idea?

Thinks for taking your time.

**Comment by lbolla** [comment]
Are you sure you are using the same version of the software? The code is the same (master branch) and the .tar.gz and .zip files are both simply archives of the same code.

**Comment by Tomatolism** [comment]
Thanks for your kind reply! 

I download both .tar.gz and .zip file from Homepage,
so I supposed they are the same version.
I will check the version again.

**Comment by Tomatolism** [comment]
Thanks for your reply helping found out the mistake I made.
I want to distinguish the import from tar.gz and .zip, so I changed the folder name in .zip file.
That's place the wrong result comes out.

Thanks for your excellent work and reply again!
