### ISSUE TITLE
Docstring for SVFDModeSolver

### ISSUE THREAD

**Issue by jtfriedl** [lbolla/EMpy#33]
It looks like the author copied and pasted this from wgmodes.m
The author should have copied and pasted from svmodes.m
The boundary conditions are not described properly in the docstring.

In SVFDModeSolver, the boundary string describes the conditions on the field being solved for (Ex, Ey, or scalar) not the Hx and Hx fields.

**Comment by lbolla** [comment]
I don't understand the issue. Please re-open and clarify.
