### ISSUE TITLE
Hardcoded addresses in FDTD.py

### ISSUE THREAD

**Issue by DanHickstein** [lbolla/EMpy#4]
What does empy.propagators.FDTD.py do?

There are some hard-coded usernames in the [`fetch_data` and `put_data` functions](https://github.com/lbolla/EMpy/blob/master/EMpy/propagators/FDTD.py#L172) that seem like they perhaps don't belong in the main EmPy package.

**Comment by lbolla** [comment]
Those are definitely leftovers, that I used to postprocess the output of an FDTD solver, not included in EMpy. They are there only for historical reasons: I think they could go now.
