### ISSUE TITLE
windows python 3.11 pip install ElectromagneticPython fails due to mismatch in version metadata

### ISSUE THREAD

**Issue by chalkie666** [lbolla/EMpy#42]
Hi!

windows python 3.11 
pip install ElectromagneticPython 
fails due to mismatch in version metadata

had to do :
pip install --upgrade --no-cache-dir --use-depreciated=legacy-resolver ElectromagneticPython
to force it to install. 

i will git clone the repo (mainly to get the examples for thin film and grating scattering) and see if its an easy fix....

Thanks for making this open source so i can independently verify the commercially provided spectra fitting programs from kla, noca, n&k etc. 

cheers

Dan

**Comment by lbolla** [comment]
I've bumped a bunch of dependencies. Can you please try again?

**Comment by lbolla** [comment]
Closing for lack of feedback.
