### ISSUE TITLE
Differences in Master and code installed with pip (version 2.0.0)

### ISSUE THREAD

**Issue by TomFD** [lbolla/EMpy#44]
Hi, I installed EMpy using

pip install ElectromagneticPython

and checked that it is installed: 

pip show ElectromagneticPython
Name: ElectroMagneticPython
Version: 2.0.0
Summary: EMpy - ElectroMagnetic Python
Home-page: http://lbolla.github.io/EMpy/
Author: Lorenzo Bolla
Author-email: code@lbolla.info
License: BSD

However, according to the master, the file FD.py contains the correct line 1369: 

`nlayers *= numpy.ones(4,dtype=int)`

but in the installed version, the line is:

`nlayers *= numpy.ones(4)`

How can that be?

Thank you,
Tom

**Comment by lbolla** [comment]
Because version 2.0.0 is from more than 3 years ago... I haven't done a release in a while. I'll see if the machinery for release still works and release 2.1. In the meantime, please use tip.
