### ISSUE TITLE
EMpy import error

### ISSUE THREAD

**Issue by langrock** [lbolla/EMpy#46]
I've been using EMpy every now and then, but am now running into an import error and am wondering if there've been changes to the numpy.testing library that conflict with EMpy. Please see the error below. Does anyone know what might be going on?

ImportError: cannot import name 'Tester' from 'numpy.testing' (C:\Users\username\AppData\Local\miniforge3\lib\site-packages\numpy\testing\__init__.py)

Thanks,
Carsten

**Comment by lbolla** [comment]
What version of numpy are you using?

**Comment by lbolla** [comment]
I've pushed a fix on master. Let me know if it works for you.
