### ISSUE TITLE
How to define periodic boundaries? 

### ISSUE THREAD

**Issue by paulxshen** [lbolla/EMpy#49]
I see `boundary = "0000"` - how to instead set periodic BC?

**Comment by lbolla** [comment]
The possible values of `boundary` are described in the docstring of `SVFDModeSolver`: https://github.com/lbolla/EMpy/blob/master/EMpy/modesolvers/FD.py#L54
I don't think the algorithm implemented in that class (see paper referenced in module docstring) described periodic boundary conditions. 
Maybe later papers have an implementation, but EMpy doesn't.
