### ISSUE TITLE
Anisotropic materials clarification

### ISSUE THREAD

**Issue by evanLsimmons** [lbolla/EMpy#50]
Hi, just looking for some clarification. For the simulation of anisotropic materials, can this code handle off diagonal matrix elements reliably? Examples look like diagonal matrices, just wanted to check. Thanks!

**Comment by dchutchings** [comment]
Yes, code supports off-diagonal xy elements, both real for birefringence and imaginary for magneto-optic effect. Note that in birefringence there is always a rotational transform to make the dielectric tensor diagonal (optical axes), but if the simulation axes are not these, then that's when you get the off-diagonal.
